//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdejaZadatak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavka
    {
        public string BrojFakture { get; set; }
        public int RedniBroj { get; set; }
        public int Kolicina { get; set; }
        public decimal Cena { get; set; }
        public decimal Ukupno { get; set; }
    
        public virtual Faktura Faktura { get; set; }
    }
}
